In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [27]:
df=pd.read_csv('student-mat.csv',sep=';')

In [28]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [30]:
catergorical=df.select_dtypes(include='object').columns

In [31]:
print(catergorical)

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [32]:
for i in catergorical:
  df[i]=le.fit_transform(df[i])

In [33]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,0,0,18,1,0,0,4,4,0,4,...,4,3,4,1,1,3,6,5,6,6
1,0,0,17,1,0,1,1,1,0,2,...,5,3,3,1,1,3,4,5,5,6
2,0,0,15,1,1,1,1,1,0,2,...,4,3,2,2,3,3,10,7,8,10
3,0,0,15,1,0,1,4,2,1,3,...,3,2,2,1,1,5,2,15,14,15
4,0,0,16,1,0,1,3,3,2,2,...,4,3,2,1,2,5,4,6,10,10

In [34]:
x=df.drop('G3',axis=1)
y=df['G3']

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [37]:
model=Sequential([
Input(shape=(32,)),
Dense(128,activation='relu'),
Dense(64,activation='relu'),
Dense(32,activation='relu'),
Dense(1,activation='relu')])

In [38]:
model.compile(optimizer='adam',loss='mse',metrics=['r2_score'])

In [39]:
model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 115.8979 - r2_score: -5.0189 - val_loss: 103.6623 - val_r2_score: -2.7574
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 82.7005 - r2_score: -3.2949 - val_loss: 66.2465 - val_r2_score: -1.4012
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 42.6468 - r2_score: -1.2148 - val_loss: 33.5261 - val_r2_score: -0.2152
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 17.8301 - r2_score: 0.0740 - val_loss: 27.5191 - val_r2_score: 0.0025
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 12.1424 - r2_score: 0.3694 - val_loss: 18.0255 - val_r2_score: 0.3466
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3852 - r2_score: 0.6165 - val_loss: 13.1959 - val_r2_score: 0.5217
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1436 - r2_score: 0.6809 - val_loss: 11.6887 - val_r2_score: 0.5763
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.0867 - r2_score: 0.7358 - val_loss: 11.4539 - val_r2_score: 0.5848
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.6094 - r2_score: 0.7606 - val_loss: 10.8691 - val_r2_score: 0.6060
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1988 - r2_score: 0.7819 - val_loss: 10.5874 - val_r2_score: 0.6162
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.8543 - r2_score: 0.7998 - val_loss: 10.6343 - val_r2_score: 0.6145
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6030 - r2_score: 0.8129 - val_loss: 10.4474 - val_r2_score: 0.6213
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3322 - r2_score: 0.8269 - val_loss: 10.1869 - val_r2_score: 0.6308
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0679 - r2_score: 0.8407 - val_loss: 10.1966 - val_r2_score: 0.6304
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8545 - r2_score: 0.8518 - val_loss: 10.1957 - val_r2_score: 0.6304
Epoch 16/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.6220 - r2_score: 0.8638 - val_loss: 10.0076 - val_r2_score: 0.6373
Epoch 17/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4247 - r2_score: 0.8741 - val_loss: 9.8911 - val_r2_score: 0.6415
Epoch 18/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.2325 - r2_score: 0.8841 - val_loss: 10.0251 - val_r2_score: 0.6366
Epoch 19/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0478 - r2_score: 0.8937 - val_loss: 9.8185 - val_r2_score: 0.6441
Epoch 20/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.8547 - r2_score: 0.9037 - val_loss: 9.7304 - val_r2_score: 0.6473
Epoch 21/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7037 - r2_score: 0.9115 - val_loss: 9.6930 - val_r2_score: 0.6487
Epoch 22/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.5635 - r2_score: 0.9188 - val_loss: 9.5369 - val_r2_score: 0.6543
Epoch 23/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.4175 - r2_score: 0.9264 - val_loss: 9.6336 - val_r2_score: 0.6508
Epoch 24/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.2798 - r2_score: 0.9335 - val_loss: 9.5976 - val_r2_score: 0.6521
Epoch 25/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.1658 - r2_score: 0.9395 - val_loss: 9.4918 - val_r2_score: 0.6560
Epoch 26/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.0468 - r2_score: 0.9456 - val_loss: 9.4759 - val_r2_score: 0.6565
Epoch 27/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9603 - r2_score: 0.9501 - val_loss: 9.4465 - val_r2_score: 0.6576
Epoch 28/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.8617 - r2_score: 0.9552 - val_loss: 9.6653 - val_r2_score: 0.6497
Epoch 29/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7887 - r2_score: 0.9590 - val_loss: 9.5077 - val_r2_score: 0.6554
Epoch 30/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.7113 - r2_score: 0.9631 - val_loss: 9.5317 - val_r2_score: 0.6545
Epoch 31/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.6425 - r2_score: 0.9666 - val_loss: 9.6060 - val_r2_score: 0.6518
Epoch 32/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.5702 - r2_score: 0.9704 - val_loss: 9.5833 - val_r2_score: 0.6526
Epoch 33/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5117 - r2_score: 0.9734 - val_loss: 9.6260 - val_r2_score: 0.6511
Epoch 34/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4568 - r2_score: 0.9763 - val_loss: 9.3262 - val_r2_score: 0.6620
Epoch 35/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4152 - r2_score: 0.9784 - val_loss: 9.7369 - val_r2_score: 0.6471
Epoch 36/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3676 - r2_score: 0.9809 - val_loss: 9.5002 - val_r2_score: 0.6557
Epoch 37/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3284 - r2_score: 0.9829 - val_loss: 9.6654 - val_r2_score: 0.6497
Epoch 38/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2927 - r2_score: 0.9848 - val_loss: 9.5202 - val_r2_score: 0.6549
Epoch 39/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2631 - r2_score: 0.9863 - val_loss: 9.7493 - val_r2_score: 0.6466
Epoch 40/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2378 - r2_score: 0.9876 - val_loss: 9.6142 - val_r2_score: 0.6515
Epoch 41/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2140 - r2_score: 0.9889 - val_loss: 9.6622 - val_r2_score: 0.6498
Epoch 42/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2017 - r2_score: 0.9895 - val_loss: 9.8846 - val_r2_score: 0.6417
Epoch 43/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1846 - r2_score: 0.9904 - val_loss: 9.4784 - val_r2_score: 0.6564
Epoch 44/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1631 - r2_score: 0.9915 - val_loss: 9.9904 - val_r2_score: 0.6379
Epoch 45/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1454 - r2_score: 0.9924 - val_loss: 9.6980 - val_r2_score: 0.6485
Epoch 46/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1278 - r2_score: 0.9934 - val_loss: 9.8731 - val_r2_score: 0.6421
Epoch 47/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1181 - r2_score: 0.9939 - val_loss: 9.7815 - val_r2_score: 0.6455
Epoch 48/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.1068 - r2_score: 0.9945 - val_loss: 9.8270 - val_r2_score: 0.6438
Epoch 49/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0981 - r2_score: 0.9949 - val_loss: 9.8850 - val_r2_score: 0.6417
Epoch 50/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0880 - r2_score: 0.9954 - val_loss: 9.9007 - val_r2_score: 0.6411
Epoch 51/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0805 - r2_score: 0.9958 - val_loss: 9.8336 - val_r2_score: 0.6436
Epoch 52/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0738 - r2_score: 0.9962 - val_loss: 9.8514 - val_r2_score: 0.6429
Epoch 53/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0672 - r2_score: 0.9965 - val_loss: 9.8855 - val_r2_score: 0.6417
Epoch 54/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0621 - r2_score: 0.9968 - val_loss: 9.9675 - val_r2_score: 0.6387
Epoch 55/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0583 - r2_score: 0.9970 - val_loss: 9.8933 - val_r2_score: 0.6414
Epoch 56/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0536 - r2_score: 0.9972 - val_loss: 9.9067 - val_r2_score: 0.6409
Epoch 57/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0485 - r2_score: 0.9975 - val_loss: 9.9103 - val_r2_score: 0.6408
Epoch 58/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0445 - r2_score: 0.9977 - val_loss: 9.9477 - val_r2_score: 0.6394
Epoch 59/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0399 - r2_score: 0.9979 - val_loss: 9.8642 - val_r2_score: 0.6425
Epoch 60/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0386 - r2_score: 0.9980 - val_loss: 9.9170 - val_r2_score: 0.6405
Epoch 61/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0343 - r2_score: 0.9982 - val_loss: 10.0010 - val_r2_score: 0.6375
Epoch 62/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0314 - r2_score: 0.9984 - val_loss: 9.9019 - val_r2_score: 0.6411
Epoch 63/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0290 - r2_score: 0.9985 - val_loss: 9.8593 - val_r2_score: 0.6426
Epoch 64/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0266 - r2_score: 0.9986 - val_loss: 9.9766 - val_r2_score: 0.6384
Epoch 65/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0246 - r2_score: 0.9987 - val_loss: 9.8849 - val_r2_score: 0.6417
Epoch 66/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0228 - r2_score: 0.9988 - val_loss: 9.9386 - val_r2_score: 0.6398
Epoch 67/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0216 - r2_score: 0.9989 - val_loss: 10.0256 - val_r2_score: 0.6366
Epoch 68/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0183 - r2_score: 0.9990 - val_loss: 9.8720 - val_r2_score: 0.6422
Epoch 69/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0193 - r2_score: 0.9990 - val_loss: 9.9311 - val_r2_score: 0.6400
Epoch 70/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0167 - r2_score: 0.9991 - val_loss: 10.0038 - val_r2_score: 0.6374
Epoch 71/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0150 - r2_score: 0.9992 - val_loss: 9.9064 - val_r2_score: 0.6409
Epoch 72/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0137 - r2_score: 0.9993 - val_loss: 9.9122 - val_r2_score: 0.6407
Epoch 73/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0131 - r2_score: 0.9993 - val_loss: 10.0559 - val_r2_score: 0.6355
Epoch 74/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0120 - r2_score: 0.9994 - val_loss: 9.9395 - val_r2_score: 0.6397
Epoch 75/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0108 - r2_score: 0.9994 - val_loss: 9.9127 - val_r2_score: 0.6407
Epoch 76/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0098 - r2_score: 0.9995 - val_loss: 10.0123 - val_r2_score: 0.6371
Epoch 77/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0093 - r2_score: 0.9995 - val_loss: 9.9735 - val_r2_score: 0.6385
Epoch 78/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0083 - r2_score: 0.9996 - val_loss: 9.9510 - val_r2_score: 0.6393
Epoch 79/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0076 - r2_score: 0.9996 - val_loss: 9.9275 - val_r2_score: 0.6402
Epoch 80/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0072 - r2_score: 0.9996 - val_loss: 9.9605 - val_r2_score: 0.6390
Epoch 81/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0066 - r2_score: 0.9997 - val_loss: 9.9654 - val_r2_score: 0.6388
Epoch 82/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0061 - r2_score: 0.9997 - val_loss: 9.9539 - val_r2_score: 0.6392
Epoch 83/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - r2_score: 0.9997 - val_loss: 9.9594 - val_r2_score: 0.6390
Epoch 84/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0053 - r2_score: 0.9997 - val_loss: 9.9795 - val_r2_score: 0.6383
Epoch 85/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0049 - r2_score: 0.9997 - val_loss: 9.9626 - val_r2_score: 0.6389
Epoch 86/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0044 - r2_score: 0.9998 - val_loss: 9.9743 - val_r2_score: 0.6385
Epoch 87/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041 - r2_score: 0.9998 - val_loss: 9.9660 - val_r2_score: 0.6388
Epoch 88/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0038 - r2_score: 0.9998 - val_loss: 9.9449 - val_r2_score: 0.6395
Epoch 89/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0036 - r2_score: 0.9998 - val_loss: 9.9393 - val_r2_score: 0.6397
Epoch 90/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033 - r2_score: 0.9998 - val_loss: 9.9783 - val_r2_score: 0.6383
Epoch 91/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0029 - r2_score: 0.9998 - val_loss: 9.9663 - val_r2_score: 0.6388
Epoch 92/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0027 - r2_score: 0.9999 - val_loss: 9.9860 - val_r2_score: 0.6380
Epoch 93/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - r2_score: 0.9999 - val_loss: 9.9664 - val_r2_score: 0.6388
Epoch 94/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024 - r2_score: 0.9999 - val_loss: 9.9874 - val_r2_score: 0.6380
Epoch 95/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - r2_score: 0.9999 - val_loss: 9.9963 - val_r2_score: 0.6377
Epoch 96/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0021 - r2_score: 0.9999 - val_loss: 9.9540 - val_r2_score: 0.6392
Epoch 97/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0020 - r2_score: 0.9999 - val_loss: 9.9666 - val_r2_score: 0.6387
Epoch 98/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018 - r2_score: 0.9999 - val_loss: 9.9626 - val_r2_score: 0.6389
Epoch 99/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016 - r2_score: 0.9999 - val_loss: 9.9789 - val_r2_score: 0.6383
Epoch 100/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0015 - r2_score: 0.9999 - val_loss: 9.9506 - val_r2_score: 0.6393

In [40]:
predict=model.predict(x_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step

In [41]:
from sklearn.metrics import r2_score

In [42]:
print(r2_score(y_test,predict))

0.6393262147903442